# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
                ('saldoDeudor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='saldo_deudor')),
                ('saldoAcreedor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='saldo_acreedor')),
                ('codigo_dependiente', models.IntegerField(null=True)),
                ('descripcion', models.CharField(default='null', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='detalleTransaccion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
            ],
        ),
        migrations.CreateModel(
            name='estadoComprobacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id_periodoContable', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(help_text='Formato: AAAA/MM/DD', verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(help_text='Formato: AAAA/MM/DD', verbose_name='Fecha de Fin')),
                ('estadoPeriodo', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_Transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=256)),
                ('fecha', models.DateField(help_text='Formato: AAAA/MM/DD', verbose_name='Fecha de Transaccion')),
                ('id_periodoContable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contables.PeriodoContable')),
            ],
        ),
        migrations.AddField(
            model_name='detalletransaccion',
            name='id_Transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contables.Transaccion'),
        ),
        migrations.AddField(
            model_name='detalletransaccion',
            name='id_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contables.Cuenta'),
        ),
    ]
