# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 02:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoResulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
            ],
        ),
    ]
