# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0004_estadoresulta_utilidadneta'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='is_inicial',
            field=models.NullBooleanField(),
        ),
    ]
