# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 11:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0005_transaccion_is_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoCapital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
                ('capitalContable', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capital Contable')),
                ('UtilidadRetenida', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Utilildad Retenida')),
            ],
        ),
    ]
