# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0008_auto_20171129_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='terminado',
            field=models.NullBooleanField(),
        ),
    ]
