# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0009_orden_terminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
