# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 23:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0010_empleado_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaFinal', models.DateField(help_text='Formato: AAAA/MM/DD', verbose_name='Fecha de Final')),
                ('cantidadFinal', models.IntegerField()),
                ('costoTotalFinal', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Final')),
                ('costoUnitarioFinal', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario FInal')),
                ('kardex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contables.Kardex')),
            ],
        ),
    ]
