# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 14:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0013_planillageneral_salarionominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillageneral',
            name='insaforp',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='INSAFORP'),
        ),
    ]
