# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0014_planillageneral_insaforp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='Formato: AAAA/MM/DD', verbose_name='Fecha de Contratacion'),
        ),
    ]
